dist: trusty
sudo: required
language: python
python: '3.5'
addons:
  apt:
    packages:
    - curl
    - python-pip
    - libssl-dev
    - python-dev
    - jq
env:
  global:
  - PACKER_VERSION=1.2.1
  - OS_AUTH_URL=https://auth.cloud.ovh.net/v2.0
  - OS_ENDPOINT_TYPE=publicURL
  - OS_INTERFACE=public
  - OS_IDENTITY_API_VERSION=2
  - OS_REGION_NAME=BHS3
  - secure: "Xs6TqEOYejU0LsboM1lWmn1Jcz/JkF+3Ae0+7Duj5//d+Vzk++hFRVkLTDIZ/HpFvF1UzxqYfCiXmQeuMxmbOpiy8xI+rXVf7rVDy5XaFDXanrBsgNite6bkBzdw1GKq8WZ9LnFBlgXIMCZSe7ffkWjNBunxPRxY/2F2nZQxV3majYm9TMDIAhI6ZIx/pgV32IY1J/FmujIwIMjYVEeU8TiUdfsrptYBMW+em9eVvc5SRGlVtVAilAsaozw3HohkwDLn6/EoJvIrIfXCW9+lImaqP0X/8KCWV/S12yWr9Mbom222Txb0bSCpsvc72B4bf+X2d5JeFgc3P+S4wwzfb6Z/jF5ckrlldKNBlD87X1oi19308wtt/runZ0ykGOCqV37ELJmC4CoIYPI7cgA/e07G9KxeENAP6ccyPPQ0zARDFtyUmQEE6p/5orvsyAwOdtejjzymbJBvPqEyibW3whp935q4HsxgxcP7oBJf0QKB0nQkgaBOMXdiN8Y6sZs+spyZzA+JKRslLbfNzjAquT8/zjIyYa+6JWR/McniCX+xAD1grx3m28Ox2MGRWAcA03ZBErxsg1QW7QB8gixPFSEBb/iFhKKeXchkCv/VuNPkRGbo5EhXf+IPEmLHtYkkYic2bAzzWEvVxT6H1B0CqYqFN+2zdgPidTpAqmaiwVA="
  - secure: "M4Fi3xqX3cbGQhCdlNkgiwtHYOJ+J/YA7CQ6ghgQ7GzzwoGeJD+EHHWG1ibhpYDHvaYwOmTCQnOEWFQi+zJ/EGMr4n9pB3tb3j07248S0ZMdmaitsIdt4ct0drnALRIXmWDn0u0I3QXm91WuxVWYU+uHqsandahfBaes/InaC5va3zdVvGfXxzXYZscXU6VZotqX31jJb+ZCUj5KyDup9yEF43iW9mgVliMjgdBPchsE2Pbh+S80v7ivYaLO7Z0Mxrsl4LbPUOTmugSZkdZEUY3PKz7O4lwz4/7H41IW7S26ji6T9kQSBCbGq2M/zPrxdB90+8mMdDsrk/7qBLhRF2WY+KN6OkHC3extfOD9DPB4HaouWwShAUC9CtVKpp3Tp3J9A1hmkbH0EbsvRHTvOWXiWqUc/62BkLuVZm4Ij6ZVf5kJcN73L5QDkKeqaHXxYz58msC1VeJ5z1TS0jON6xpxZ1kIHTl6/QFsUVmMUkvyIrhYYd2rQJSCmj2X84vxIftEvAHuJyYOyIIEaaYgK6a8gAIz79YlmvTYofiToySthOw6KZEfWomRbGWMrPsQ4sOkoK48I0Gf5QPjEcYPGyS8EIU7hkjU5/70jaaA/J7KX6MH82dJmvBsa6Mqxqzvk0Ax338tF5Oiney9BWEz74V4T/bIpzs6mrZpQibgP9s="
  - secure: "Z5PgjZSKtMQ6/psyPdKQdj+OnHvsBs6sA/qXUbOuEFjzcUe4zIGViK61PN8KyOVB5cvG1PMKarCgR178+GvY/qZ7l4LPujTxoYZzpCJ0iSKCniTC5p/SHnNPjajVEeJTQdv7DTvg6Csj+BL0vKVpFVW4wmAEqTQM7M2vmtOq58MRo3I+ph4ojrE/PmgKt34XcthiUZyF1KI91fVg0QIitwVDqFZjvAZauCxfrRH5guptk4By7BvKWOmZ2ObEvSB2aCB1AG60XCNUoIVNgvnDG9jWdY0usi+xwBDMqFuUe6W4mbHti/aiUBJzx8zQz+Td3WIKhVnfX1jySWq4DoyvWveFMVJdSw7ApsUJIe1smGExZxDdmr2l7bdM+CGlG6Mzzi7KAAzjiicyfSweVxt6yI9itMP4LjA7xj8mLQUyD2DrkzMYTtGV8Iwi7BnaLzysscP5p0hacIdG+J7JXDrqNZCtHw7dbthCrWGXOcSF8iIVgDJcSrwtcxQ901EpX4+Xc10oTjEAI+xGNC+YXhDR8ynFnKfBRnewOnzhjrQ+3tmu1/S9YYTwO+rZGXOoFVjz2COn/DLSYYxdwYO3jBywoyijibPYj1yJ4jeRuJFj1mDfmRDki4gA8qtcxjAuG8ZVQJyJmgoGwe7YL8Qu67yN6/HRtldSLzr83MSYGyXAVpA="
  - secure: "bIskaIwvvvyJd5fm2bGMbToKMJt5oQEC+K5hCqskNtsvrTYwGBfUPB0kwVfFBcojbjN6phqkvJ1r8PkbIMjJOqz6e/ajD6kUlzglTZb9KOWZmMA+RscKiaQYR1dlhHddcdl2UpRhFIlzmOU0OP1grOq40Gnz7DYxIxs+2dnkmDH4+j9IsOJSuttRcxD1gNrhbSvEu2MX8wiaDlfSbEVll0Qob37FkCumNmf4D+mzIRjVLJeXF6OcgWCuSJGD2VLQaKwgdf+6EOo3phRGyYEXGVyYQe5aUbNFKdg/EGvrUEt7OxcPXruhhZmyl1EoPbHSdzcxcaeMGIOX7Tqgbo9cA+dwyf1bn/3CkFlx1Lv5TUG6grFrdR3itgpNse0+hJi/bPBXqb8UzykriDBZRdTHozbuLZ+8ux62Zkra/5Bs42s25tFR7sJAyE82MUvbNF9BALF31cVFjEM+xrbfjJIpE516Sa/oZlP2LJdHV1mpiVEW0t0/FFN/Z8vU577MoZ9b9e0pd0mUvOG9j/FqckmuTw19R3jOsPKWJwnfb1W/ybxXPHZJAybm+BbAXFBH+MmWARr5W70ev5njAN+vszW/iYZZhDAScfb5Y2/5LTsy3tLWNfSD8tgtb7iJ2uc63RE3U0TAbRRObtEPNL3QGfuC5VGAJ28Y+fZGYpdxFr8Hw/0="
  - secure: "vC4vJpSyMue2EKunNp3Hwn6GVG4mD+s34EBhDA0FODFBn59smKTDFaag/dh6UZ9m7dgew4f9pE3sZRJdBSd8/MYFEbveEboZiYMjHfk1qtm4hfpUozc88XuRZMVUBp2ySOs7F4i5DGiNbHEPQq5w1tjAQJ28u1YxqQTWJw3bGsHYq6b5Tyb7MS9YfzrJFPKhFsXRGnjCA1dZ2/1yUF/xqFydeuxULi2RoyCsP12VoFteAO2GisMAwWr5oWzfilNSeA27CzMPXZtz0X90ZKak9jk7cX2JGx3dMXU4LXDr/Wtc4W/klMqkW7rIC9Ua3URH1IqTC4Of6IBGuBn+7wlmdxFOeEw2FniCnBSNag3bLdDukLbU9xqmJOhLpR/ftoTnj9skW6lTCHVo4dlo0zh6ZkR+mQWOKq8njlMBuNafNixhHLNPxD/rMylleHroJ6phgsCIYh72MnDXoSd9QpwrtgmW4Hch2dk1vJ864tZXx1dW8gR9/QRyuyHYXC8hL5WT03U3s0orBS9QFwWBewwSGTigk/0LpEN5RdloLcWdNdaM3aQkpCt4+PV3SITMXm5JF65jv9wsmfVYwayqcQ/CAaENRZe2wLI4GVzxpSGewDQZocPLmA/R49QHZbkJJmIojmbj41R/NA/Wad72UwB1717slHU8eaksI+V8G9pD1FY="
before_install:
- openssl aes-256-cbc -K $encrypted_28df513f2d13_key -iv $encrypted_28df513f2d13_iv -in .lookatch.travis.gpg.enc -out .lookatch.travis.gpg -d
- "./test/travis_setup.sh"
install:
- pip install jinja2 cffi ansible
jobs:
  include:
  - stage: build
    script: test/run.sh $IMAGE $OS_REGION_NAME && travis_wait 50 && test/publish.sh $IMAGE $OS_REGION_NAME
    env: IMAGE="packer-lookatch.json"
stages:
- build
branches:
  only:
  - master
